<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [2]:
#Cargar archivo csv desde COLAB
#from google.colab import files
#files.upload()

In [3]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('inmuebles2.csv')
data.head(5)

,Unnamed: 0,Esta es una base de datos que describe las operaciones inmobiliarias de una empresa,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,0,Referencia,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291,2133903,2004-06-19 00:00:00,Carmen
2,2,2,2004-01-01 00:00:00,Local,Venta,Girona,185,1945424,2004-04-19 00:00:00,Pedro
3,3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82,NaN,2004-11-08 00:00:00,Joaquín
4,4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285,NaN,2004-04-27 00:00:00,Jesús

In [4]:
#Eliminar primera fila o filas innecesarias
data1= pd.read_csv('inmuebles2.csv', skiprows=1)
data1

,0,Referencia,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2,2,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,5,5,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...,...,...
3332,3333,3333,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,3334,3334,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,3335,3335,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,3336,3336,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,3337,3337,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [5]:
#Eliminar columnas innecesarias
#axis = 1 para columnas
#axis = 0 para filas
data2= data1.drop(['0','Referencia'], axis=1) #axis = 0 se refiere a filas, axis = 1 se refiere a columnas, le estamos diciendo que busque esto en las columnas
data2

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [6]:
#Identificar valores nulos por columna
valores_nulos=data2.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        4
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

In [7]:
#Identificar valores nulos por dataframe
valores_nulos=data2.isnull().sum().sum()
valores_nulos

np.int64(1175)

**Métodos de Sustitución de Valores Nulos**

In [8]:
#Realizamos una copia del dataframe
data3=data2.copy()

In [9]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data3["Superficie"]=data3["Superficie"].fillna(round(data2["Superficie"].mean(),1))

In [10]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

In [11]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos con mediana
data3["Precio Venta"]=data3["Precio Venta"].fillna(round(data2["Precio Venta"].median(),1))

In [12]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta     578
Vendedor        578
dtype: int64

In [13]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
data3["Fecha Alta"]= data3["Fecha Alta"].fillna(10) 
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1121906.0,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1121906.0,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,NaN,NaN

In [14]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta     578
Vendedor        578
dtype: int64

In [15]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data3["Fecha Venta"] =data3["Fecha Venta"].fillna("2030-06-19 00:00:00")

In [16]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [17]:
#Quinto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
data3["Tipo"] =data3["Tipo"].ffill() ##ff= forwardfill recorre columnas y cuando encuentra un valor nulo, lo llena con el valor anterior

In [18]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              0
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [19]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
#Filtro por columnas
data3["Operación"] =data3["Operación"].bfill() ##valor previo del recorrido

In [20]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              0
Operación         0
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [21]:
#Sustituir valores nulos por valores no nulos hacia atrás backward fill" ("bfill")
data3["Provincia"] =data3["Provincia"].bfill()

In [22]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              0
Operación         0
Provincia         0
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [23]:
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
#Filtro por columnas
data3["Vendedor"] =data3["Vendedor"].ffill()

In [24]:
#Corroboramos valores nulos
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta      0
Tipo            0
Operación       0
Provincia       0
Superficie      0
Precio Venta    0
Fecha Venta     0
Vendedor        0
dtype: int64

In [25]:
#Corroboramos valores nulos en todo el dataframe
valores_nulos=data3.isnull().sum().sum()
valores_nulos

np.int64(0)

**Método de Eliminación de valores nulos**

In [26]:
#Identificar valores nulos por columna
valores_nulos=data2.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        4
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

In [27]:
#Realizamos una copia del dataframe
data4=data2.copy()
data4

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [28]:
#Eliminamos filas con nulos
#No se agrega nada para eliminar filas y 1 para eliminar columnas
data4= data2.dropna()
data4

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
5,2004-01-03 00:00:00,Industrial,Alquiler,Girona,131.0,953156.0,2004-09-05 00:00:00,Pedro
7,2004-01-03 00:00:00,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31 00:00:00,Jesús
...,...,...,...,...,...,...,...,...
3016,2006-12-30 00:00:00,Casa,Alquiler,Barcelona,264.0,1060488.0,2007-04-28 00:00:00,Joaquín
3017,2006-12-31 00:00:00,Oficina,Venta,Lleida,69.0,483828.0,2007-05-05 00:00:00,Pedro
3030,2007-01-07 00:00:00,Industrial,Alquiler,Lleida,196.0,904344.0,2007-04-20 00:00:00,Pedro
3042,2007-01-09 00:00:00,Local,Venta,Lleida,92.0,709596.0,2007-04-17 00:00:00,Carmen
3045,2007-01-10 00:00:00,Parking,Venta,Barcelona,233.0,1077858.0,2007-04-30 00:00:00,María

In [29]:
#Identificar valores nulos por columna
valores_nulos=data4.isnull().sum()
valores_nulos

Fecha Alta      0
Tipo            0
Operación       0
Provincia       0
Superficie      0
Precio Venta    0
Fecha Venta     0
Vendedor        0
dtype: int64

**Comparamos DataFrame3(Sustitución) y Dataframe4(Eliminación)**

In [30]:
data3.info()

<class 'pandas.DataFrame'>
RangeIndex: 3337 entries, 0 to 3336
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha Alta    3337 non-null   object
 1   Tipo          3337 non-null   str
 2   Operación     3337 non-null   str
 3   Provincia     3337 non-null   str
 4   Superficie    3337 non-null   float64
 5   Precio Venta  3337 non-null   float64
 6   Fecha Venta   3337 non-null   str
 7   Vendedor      3337 non-null   str
dtypes: float64(2), object(1), str(5)
memory usage: 208.7+ KB

In [31]:
data4.info() #el problema con eliminar datos es que puede que se pierda la representatividad

<class 'pandas.DataFrame'>
Index: 2747 entries, 0 to 3045
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha Alta    2747 non-null   str
 1   Tipo          2747 non-null   str
 2   Operación     2747 non-null   str
 3   Provincia     2747 non-null   str
 4   Superficie    2747 non-null   float64
 5   Precio Venta  2747 non-null   float64
 6   Fecha Venta   2747 non-null   str
 7   Vendedor      2747 non-null   str
dtypes: float64(2), str(6)
memory usage: 193.1 KB

**Convertir DataSet sin valores nulos a CSV**

In [32]:
#Convertir DataFrame a CSV
data3.to_csv("inmuebles_sin_nulos.csv")

In [33]:
#descargar archivo filtrado en csv
#from google.colab import files 
  
  
#files.download("inmuebles_sin_nulos.csv")

In [ ]:
##LIMPIEZA DE NULOS EN CSV 

##ACTIVIDAD 2.2
df_nulos = pd.read_csv('Copia de Citas_Digital_Filtrado.csv')
df_nulos.head(5)

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,NaN,Guillermo,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,NaN,Roberto,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,NaN,Irving,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,NaN,Oswaldo,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,NaN,Rodrigo,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...

In [35]:
df_nulos.columns

Index(['BDC ', 'Fecha', 'Nombre Cliente ', 'Estatus de Lead',
       'Potencial de compra', 'PDM', 'SDC', 'Venta', 'Asesor Asignado',
       '¿Por que no ha visitado la agencia?',
       '¿Por que no hay solicitud de credito?',
       '¿Por que no hubo prueba de manejo ?', '¿Por que no hubo proceso wow?',
       '¿Por que se asigno antes de vistar piso?'],
      dtype='str')

In [36]:
df_nulos.isnull().sum()

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         180
¿Por que no hay solicitud de credito?       294
¿Por que no hubo prueba de manejo ?         318
¿Por que no hubo proceso wow?               309
¿Por que se asigno antes de vistar piso?    320
dtype: int64

In [ ]:
#Para esta columna decidí rellenas los valores nulos por el texto "Se ignora" ya que 
#al albergar nombres, son datos que no podemos imputar sin generar sesgos
df_nulos['BDC '] = df_nulos['BDC '].fillna("Se ignora")

In [ ]:
#Para columna de fecha, cree una nueva columna con el nombre de "Mes" 
#y por medio de rangos asigné la fecha correspondiente a los registros, incluyendo mes y año
#correspondiente.

#Posteriormente reemplacé la columna original de "Fecha" por esta nueva columna.


df_nulos["Mes"] = None

In [39]:
df_nulos.loc[0:30, "Mes"] = "2025-04"
df_nulos.loc[34:58, "Mes"] = "2025-05"
df_nulos.loc[61:86, "Mes"] = "2025-06"
df_nulos.loc[88:120, "Mes"] = "2025-07"
df_nulos.loc[122:166, "Mes"] = "2025-08"
df_nulos.loc[168:230, "Mes"] = "2025-09"
df_nulos.loc[232:290, "Mes"] = "2025-10"
df_nulos.loc[292:343, "Mes"] = "2025-11"
df_nulos.loc[345:391, "Mes"] = "2025-12"

df_nulos.loc[393:428, "Mes"] = "2026-01"
df_nulos.loc[430:460, "Mes"] = "2026-02"
df_nulos.loc[462:477, "Mes"] = "2026-03"
df_nulos.loc[479:533, "Mes"] = "2026-04"
df_nulos.loc[540:598, "Mes"] = "2026-05"

fechas_reales = pd.to_datetime(df_nulos["Fecha"], errors="coerce")

df_nulos.loc[600:672, "Mes"] = (
    fechas_reales.loc[600:672]
    .dt.to_period("M")
    .astype("string")
)

In [40]:
df_nulos[["BDC ", "Fecha", "Nombre Cliente ", "Mes"]].tail(80)

         BDC        Fecha           Nombre Cliente       Mes
593  Ignacio          NaN      Yolanda Castellanos   2026-05
594      Ana          NaN                Juan Roque  2026-05
595  Igancio          NaN  Maria guadalupe Serrano   2026-05
596       Ana         NaN    MARCO ANTONIO CHARTUNI  2026-05
597       Ana         NaN                   Alexey   2026-05
..        ...         ...                       ...      ...
668  Ignacio   2026-07-21        Carlos Balderrama   2026-07
669  Ignacio   2026-07-21        Andrés Netzahuatl   2026-07
670       Ana  2026-07-22               Arat Israel  2026-07
671       Ana  2026-07-22           Maira Escalante  2026-07
672  Ignacio   2026-07-22              Zaira Macip   2026-07

[80 rows x 4 columns]

In [41]:
df_nulos["Mes"].value_counts().sort_index()

Mes
2025-04    31
2025-05    25
2025-06    26
2025-07    34
2025-08    45
2025-09    63
2025-10    59
2025-11    52
2025-12    47
2026-01    36
2026-02    31
2026-03    16
2026-04    55
2026-05    59
2026-06    44
2026-07    27
Name: count, dtype: int64

In [42]:
df_nulos["Mes"].isnull().sum()

np.int64(23)

In [43]:
# 3. Ver únicamente las filas que no tienen mes
df_nulos[df_nulos["Mes"].isnull()]

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Mes
31,Citas efectivas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
32,Saul,NaN,13,11,Ventas,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
33,MAYO,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
59,Se ignora,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
60,JUNIO,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
87,Se ignora,NaN,Julio,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
121,Se ignora,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
167,SEPTIEMBRE,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
231,OCTUBRE,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
291,NOVIEMBRE,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
344,DICIEMBRE,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
392,2026-01-01 00:00:00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
429,2026-02-01 00:00:00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
461,2026-03-01 00:00:00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
478,2026-04-01 00:00:00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
534,Se ignora,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
535,Se ignora,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
536,Se ignora,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
537,Se ignora,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
538,Se ignora,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
539,2026-05-01 00:00:00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
599,2026-06-01 00:00:00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None
641,2027-07-01 00:00:00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,<NA>

In [ ]:
## Aquí comprobé que los registros nulos que había en mi columna de mes se debía a 
# filas basura (la mayoría, filas de separación entre meses) que podían ser eliminadas sin problema.
df_nulos[df_nulos["Mes"].isnull()][["BDC ", "Fecha", "Nombre Cliente ", "Estatus de Lead"]]

                    BDC  Fecha Nombre Cliente  Estatus de Lead
31       Citas efectivas   NaN             NaN             NaN
32                 Saul    NaN              13              11
33                  MAYO   NaN             NaN             NaN
59             Se ignora   NaN             NaN             NaN
60                 JUNIO   NaN             NaN             NaN
87             Se ignora   NaN           Julio             NaN
121            Se ignora   NaN             NaN             NaN
167           SEPTIEMBRE   NaN             NaN             NaN
231              OCTUBRE   NaN             NaN             NaN
291            NOVIEMBRE   NaN             NaN             NaN
344            DICIEMBRE   NaN             NaN             NaN
392  2026-01-01 00:00:00   NaN             NaN             NaN
429  2026-02-01 00:00:00   NaN             NaN             NaN
461  2026-03-01 00:00:00   NaN             NaN             NaN
478  2026-04-01 00:00:00   NaN             NaN             NaN
534            Se ignora   NaN             NaN             NaN
535            Se ignora   NaN             NaN             NaN
536            Se ignora   NaN             NaN             NaN
537            Se ignora   NaN             NaN             NaN
538            Se ignora   NaN             NaN             NaN
539  2026-05-01 00:00:00   NaN             NaN             NaN
599  2026-06-01 00:00:00   NaN             NaN             NaN
641  2027-07-01 00:00:00   NaN             NaN             NaN

In [ ]:
# Eliminación de las filas con datos nulos en "Mes"
df_limpio = df_nulos.dropna(subset=["Mes"]).copy()

In [46]:
df_limpio["Mes"].isnull().sum()

np.int64(0)

In [ ]:
# Eliminación de columna original "Fecha"
df_limpio = df_limpio.drop(columns=["Fecha"])

# Renombre, cambiamos Mes por Fecha
df_limpio = df_limpio.rename(columns={"Mes": "Fecha"})

In [48]:
#Nueva columna en nueva posición
fecha = df_limpio.pop("Fecha")
df_limpio.insert(1, "Fecha", fecha)

In [ ]:
df_limpio.isnull().sum()

## Al eliminar las filas basura mencionadas anteriromente, también se eliminaron los nulos 
# de PDM y SDC

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                              13
Potencial de compra                          52
PDM                                           0
SDC                                           0
Venta                                         3
Asesor Asignado                               9
¿Por que no ha visitado la agencia?         157
¿Por que no hay solicitud de credito?       271
¿Por que no hubo prueba de manejo ?         295
¿Por que no hubo proceso wow?               286
¿Por que se asigno antes de vistar piso?    297
dtype: int64

In [50]:
df_limpio.columns

Index(['BDC ', 'Fecha', 'Nombre Cliente ', 'Estatus de Lead',
       'Potencial de compra', 'PDM', 'SDC', 'Venta', 'Asesor Asignado',
       '¿Por que no ha visitado la agencia?',
       '¿Por que no hay solicitud de credito?',
       '¿Por que no hubo prueba de manejo ?', '¿Por que no hubo proceso wow?',
       '¿Por que se asigno antes de vistar piso?'],
      dtype='str')

In [ ]:
# Esta columna la consideré como un caso similar a la columna de "BDC ", al ser columna cualitativa 
# creo importante no sesgar la información con moda o algo similar, ya que supongo que este estatus tendrá más factores o info relevante asociada.
df_limpio["Estatus de Lead"] = (df_limpio["Estatus de Lead"].fillna("No hay registro"))

In [54]:
df_limpio["Potencial de compra"] = pd.to_numeric(df_limpio["Potencial de compra"],errors="coerce")

In [ ]:
# Inicialmente había llenado las celdas vacía con NaN, debido a que igual que en el caso
# de "Estatus de Lead" considero que esta columna debe estar asociada a más factores y podría ser sesgada fácilmente
# sin embargo como seguíann apareciendo como valores nulos, al ser datos cuantitativos, 
# decidí implmentar la mediana, un dato más representativo que la media.

mediana_potencial = df_limpio["Potencial de compra"].median()

df_limpio["Potencial de compra"] = (df_limpio["Potencial de compra"].fillna(mediana_potencial))

In [58]:
mediana_potencial

np.float64(0.75)

In [59]:
df_limpio.tail()

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
668,Ignacio,2026-07,Carlos Balderrama,Activo,0.50,1.0,1.0,1.0,Mario Varela,NaN,NaN,NaN,NaN,NaN
669,Ignacio,2026-07,Andrés Netzahuatl,Activo,0.50,0.0,0.0,0.0,Mauricio,NaN,NaN,NaN,NaN,NaN
670,Ana,2026-07,Arat Israel,Activo,0.75,1.0,1.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN
671,Ana,2026-07,Maira Escalante,Activo,0.80,1.0,1.0,0.0,Pedro Antonio,NaN,NaN,NaN,NaN,NaN
672,Ignacio,2026-07,Zaira Macip,Activo,0.50,0.0,0.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN

In [60]:
df_limpio[df_limpio["Venta"].isnull()]

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
36,Saul,2025-05,Antonio,Finalizado,0.9,1.0,0.0,NaN,Mauricio,Visito la Agencia el dia 1 de Mayo,Por que primero quiere vender su sentra,Realizo PDM en Emkoo,Si hubo por parte del asesor,Se asigna en la visita
44,Saul,2025-05,Gerardo garcia,Finalizado,0.6,1.0,0.0,NaN,Eduardo,Ya nos visito el dia 13 de mayo,Pide que su mensualidad no exceda los 6mil,Si hubo prueba de manejo,"recibio la atencion, se fue muy contento",Se asigno hasta el momento de la visita
88,Saul,2025-07,Hugo Martines,Activo,0.6,1.0,1.0,NaN,Alan,Ya nos visito el dia 01 de Juio,Esta en proceso por ensueño,Si realizo la prueba de manejo,Recibio la atencion,Se asigna en la visita

In [ ]:
## Al ser una variable binaria, decidí reemplazar los pocos valores nulos con la moda.
moda_venta = df_limpio["Venta"].mode()[0]
df_limpio["Venta"] = df_limpio["Venta"].fillna(moda_venta)

In [ ]:
## Igual que en "BDC", al ser NOMBRES de los asesores de la empresa, 
# decidí llenar las celdas con "Se ignora" para no generar mala info.
df_limpio['Asesor Asignado'] = df_limpio['Asesor Asignado'].fillna("Se ignora")

In [63]:
df_limpio.isnull().sum()

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?         157
¿Por que no hay solicitud de credito?       271
¿Por que no hubo prueba de manejo ?         295
¿Por que no hubo proceso wow?               286
¿Por que se asigno antes de vistar piso?    297
dtype: int64

In [ ]:
## Estas últimas columnas decidí tratarlas de la misma manera, ya que al ser texto preferí llenar 
# los valores nulos con 'No hay reggistro'.

texto = ['¿Por que no ha visitado la agencia?','¿Por que no hay solicitud de credito?','¿Por que no hubo prueba de manejo ?','¿Por que no hubo proceso wow?','¿Por que se asigno antes de vistar piso?']
df_limpio[texto] = df_limpio[texto].fillna('No hay registro')

In [65]:
df_limpio.isnull().sum()

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         0
SDC                                         0
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

In [66]:
df_limpio.to_csv("Citas_Digital_sin_nulos.csv")