In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('Plazas.xlsx')
df.head()

,Fecha Origen,Nombre,Telefono,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,2025-05-06 18:30:00,Alejandro Fernandez,NaN,AION,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Recibe recurso a finales de junio, proyección ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-05-06 18:00:00,David Israel,NaN,EMKOO,JOSE EDUARDO PARADA DURAN,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Finalizado,Si hay seguimiento,Dejo de contestar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-05-06 13:50:00,Rosendo Ceron,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-05-06 13:47:00,Fausto Ochoa Martinez,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-05-06 13:43:00,Brigida Lara Perez,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048574 entries, 0 to 1048573
Data columns (total 20 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   Fecha Origen                              302 non-null      object
 1   Nombre                                    303 non-null      str
 2   Telefono                                  0 non-null        float64
 3   Producto                                  303 non-null      str
 4   Asesor                                    303 non-null      str
 5   Origen                                    303 non-null      str
 6   Seguimiento                               1048567 non-null  float64
 7   Cita efetiva                              1048564 non-null  float64
 8   PDM                                       1048563 non-null  float64
 9   SDC                                       1048563 non-null  float64
 10  Estatus                                   1048567 non-null  object
 11  ¿Por que no hay seguimiento?              199 non-null      str
 12  ¿Por que no ha visitado la agencia?       169 non-null      str
 13  ¿Por que no hubo prueba de manejo ?       28 non-null       str
 14  ¿Por que no hubo solicitud de credito?    27 non-null       str
 15  ¿Por que no se ha formalizado la compra?  14 non-null       str
 16  Unnamed: 16                               24 non-null       str
 17  Unnamed: 17                               0 non-null        float64
 18  Unnamed: 18                               0 non-null        float64
 19  Unnamed: 19                               1 non-null        str
dtypes: float64(7), object(2), str(11)
memory usage: 160.0+ MB

In [4]:
df.isnull().sum()

Fecha Origen                                1048272
Nombre                                      1048271
Telefono                                    1048574
Producto                                    1048271
Asesor                                      1048271
Origen                                      1048271
Seguimiento                                       7
Cita efetiva                                     10
PDM                                              11
SDC                                              11
Estatus                                           7
¿Por que no hay seguimiento?                1048375
¿Por que no ha visitado la agencia?         1048405
¿Por que no hubo prueba de manejo ?         1048546
¿Por que no hubo solicitud de credito?      1048547
¿Por que no se ha formalizado la compra?    1048560
Unnamed: 16                                 1048550
Unnamed: 17                                 1048574
Unnamed: 18                                 1048574
Unnamed: 19                                 1048573
dtype: int64

In [5]:
df.columns

Index(['Fecha Origen', 'Nombre', 'Telefono', 'Producto', 'Asesor', 'Origen',
       'Seguimiento', 'Cita efetiva ', 'PDM', 'SDC', 'Estatus',
       '¿Por que no hay seguimiento?', '¿Por que no ha visitado la agencia?',
       '¿Por que no hubo prueba de manejo ?',
       '¿Por que no hubo solicitud de credito?',
       '¿Por que no se ha formalizado la compra?', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19'],
      dtype='str')

In [6]:
df = df.drop(columns=["Telefono"])

In [7]:
df.iloc[270:290]

,Fecha Origen,Nombre,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
270,2025-06-02 10:35:00,Fernanda Tadeo,EMZOOM,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,2025-06-02 10:28:00,Wendy Cruz,GS8,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,1.0,1.0,1.0,0.0,Contactado,Si hay seguimiento,Ya visito la agencia,Ya hizo prueba,Esta evaluando opciones,NaN,NaN,NaN,NaN,NaN
272,2025-06-02 10:22:00,Francisco Javier Cianka,GN8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Finalizado,Si hay seguimiento,Dejo de contestar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,2025-06-02 10:21:00,Eduardo,GS8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Cita dom 8, no asistio el cliente",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,2025-06-02 10:06:00,Alejandro,GS8,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,False,Si hay seguimiento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,2025-06-02 10:04:00,Margarita Guzman,GS8,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,False,Si hay seguimiento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,2025-06-01 19:36:00,Estela Martinez,EMZOOM,Carlos Cortes Texis,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,2025-06-01 19:36:00,Argeni Morales,EMZOOM,Carlos Cortes Texis,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.iloc[1048540:1048560]

,Fecha Origen,Nombre,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
1048540,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048541,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048542,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048543,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048544,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048545,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048546,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048547,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048548,2025-06-02 10:24:13,Catalin,Emzoom,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,1.0,1.0,1.0,NaN,Contactado,Si hay seguimiento,"Esta vendiendo su camioneta, cita miercoles 11",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048549,2025-06-10 19:46:00,Nancy Gonzalez,EMZOOM,RICARDO SILVA HERAS,PLAZA ANGELOPOLIS,1.0,NaN,NaN,NaN,Contactado,Si hay seguimiento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048550,2025-06-10 19:25:00,Diego Flores,GS8,RICARDO SILVA HERAS,PLAZA ANGELOPOLIS,1.0,NaN,NaN,NaN,Contactado,Si hay seguimiento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048551,2025-06-10 18:57:00,Andres Morgan,GS8,VICTOR MANUEL SANCHEZ ARROYO,GALERIAS TLAXCALA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048552,2025-06-10 18:53:00,Cesar Xicohtencatl,GS8,VICTOR MANUEL SANCHEZ ARROYO,Gran Patio Tlaxcala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048553,2025-06-10 18:04:00,Jesus Fernandez,GS8,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048554,2025-06-10 17:39:00,Agustin .,EMKOO,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048555,2025-06-10 17:37:00,Claudia Aguilar,GS8,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048556,2025-06-10 17:17:00,Miguel Angel Perez Mendez,EMZOOM,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048557,2025-06-10 17:14:00,Liam Nieto,GS8,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048558,2025-06-10 17:09:00,Marcos Paredes Juarez,EMZOOM,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048559,2025-06-10 16:48:00,Elena Covarrubias,GS8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df = df.drop(df.index[278:1048548])

In [10]:
df.isnull().sum()

Fecha Origen                                  2
Nombre                                        1
Producto                                      1
Asesor                                        1
Origen                                        1
Seguimiento                                   7
Cita efetiva                                 10
PDM                                          11
SDC                                          11
Estatus                                       7
¿Por que no hay seguimiento?                105
¿Por que no ha visitado la agencia?         135
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
Unnamed: 16                                 280
Unnamed: 17                                 304
Unnamed: 18                                 304
Unnamed: 19                                 303
dtype: int64

In [11]:
df = df.reset_index(drop=True)
df.iloc[270:290]

,Fecha Origen,Nombre,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
270,2025-06-02 10:35:00,Fernanda Tadeo,EMZOOM,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,2025-06-02 10:28:00,Wendy Cruz,GS8,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,1.0,1.0,1.0,0.0,Contactado,Si hay seguimiento,Ya visito la agencia,Ya hizo prueba,Esta evaluando opciones,NaN,NaN,NaN,NaN,NaN
272,2025-06-02 10:22:00,Francisco Javier Cianka,GN8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Finalizado,Si hay seguimiento,Dejo de contestar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,2025-06-02 10:21:00,Eduardo,GS8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Cita dom 8, no asistio el cliente",NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,2025-06-02 10:06:00,Alejandro,GS8,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,False,Si hay seguimiento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,2025-06-02 10:04:00,Margarita Guzman,GS8,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,False,Si hay seguimiento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,2025-06-01 19:36:00,Estela Martinez,EMZOOM,Carlos Cortes Texis,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,2025-06-01 19:36:00,Argeni Morales,EMZOOM,Carlos Cortes Texis,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,2025-06-02 10:24:13,Catalin,Emzoom,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,1.0,1.0,1.0,NaN,Contactado,Si hay seguimiento,"Esta vendiendo su camioneta, cita miercoles 11",NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,2025-06-10 19:46:00,Nancy Gonzalez,EMZOOM,RICARDO SILVA HERAS,PLAZA ANGELOPOLIS,1.0,NaN,NaN,NaN,Contactado,Si hay seguimiento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,2025-06-10 19:25:00,Diego Flores,GS8,RICARDO SILVA HERAS,PLAZA ANGELOPOLIS,1.0,NaN,NaN,NaN,Contactado,Si hay seguimiento,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,2025-06-10 18:57:00,Andres Morgan,GS8,VICTOR MANUEL SANCHEZ ARROYO,GALERIAS TLAXCALA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,2025-06-10 18:53:00,Cesar Xicohtencatl,GS8,VICTOR MANUEL SANCHEZ ARROYO,Gran Patio Tlaxcala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,2025-06-10 18:04:00,Jesus Fernandez,GS8,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,2025-06-10 17:39:00,Agustin .,EMKOO,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,2025-06-10 17:37:00,Claudia Aguilar,GS8,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,2025-06-10 17:17:00,Miguel Angel Perez Mendez,EMZOOM,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,2025-06-10 17:14:00,Liam Nieto,GS8,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,2025-06-10 17:09:00,Marcos Paredes Juarez,EMZOOM,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,2025-06-10 16:48:00,Elena Covarrubias,GS8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.tail()

,Fecha Origen,Nombre,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
299,2025-06-09 15:30:00,Miguel Fernandez,GS8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,2025-06-09 13:15:00,Luis,EMZOOM,SERGIO RAYMUNDO VAZQUEZ SANCHEZ,GALERIAS TLAXCALA,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,2025-06-09 13:14:00,Rolando Manrique,EMZOOM,SERGIO RAYMUNDO VAZQUEZ SANCHEZ,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,2025-06-09 12:50:00,Odilia Cuamatzi Bautista,GS8,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,2025-05-24 12:19:22,Raul Jimenez,EMZOOM,RICARDO SILVA HERAS,PLAZA ANGELOPOLIS,1.0,NaN,NaN,NaN,Contactado,Si hay seguimiento,Esta preautorizado,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.isnull().sum()

Fecha Origen                                  2
Nombre                                        1
Producto                                      1
Asesor                                        1
Origen                                        1
Seguimiento                                   7
Cita efetiva                                 10
PDM                                          11
SDC                                          11
Estatus                                       7
¿Por que no hay seguimiento?                105
¿Por que no ha visitado la agencia?         135
¿Por que no hubo prueba de manejo ?         276
¿Por que no hubo solicitud de credito?      277
¿Por que no se ha formalizado la compra?    290
Unnamed: 16                                 280
Unnamed: 17                                 304
Unnamed: 18                                 304
Unnamed: 19                                 303
dtype: int64

In [14]:
df.shape

(304, 19)

In [15]:
## Decidí eliminar directamente las columnas: Unnamed 17 y 18 debido a que no tienen un solo registro.
# Eliminé: unnamed 19 porque solo tiene 1 valor no nulo
# Eliminé unnamed 16 porque no tenía info clara ni un nombre acorde al contenido de la columna.

df = df.drop(columns=["Unnamed: 16","Unnamed: 17", "Unnamed: 18","Unnamed: 19"])

In [16]:
## Ver dónde están los nulos
df[df["Fecha Origen"].isnull()]

,Fecha Origen,Nombre,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?
108,NaN,Martin Aguilar,GS8,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,1.0,1.0,1.0,0.0,Facturado,NaN,NaN,NaN,NaN,NaN
153,NaN,Jesus Ramos,EMZOOM,Carlos Cortes Texis,Gran Patio Tlaxcala,1.0,1.0,0.0,1.0,Facturado,Si hay seguimiento,Ya visito la agencia,NaN,Ya se hizo solicitud de credito,Ya se aparto

In [17]:
# Rellené fechas faltantes con la fecha anterior, ya que sólo eran 2 registros faltantes 
df["Fecha Origen"] = df["Fecha Origen"].ffill()

In [18]:
df[df["Nombre"].isnull()]

,Fecha Origen,Nombre,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?
194,JUNIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
## Se elimina la fila basura (fila de separación) comprobada en el código anterior, 
# con lo que se eliminan los valores nulos de Nombre, Producto, Asesor y Origen.
df = df.drop(index=194)
df = df.reset_index(drop=True)

In [20]:
df.isnull().sum()

Fecha Origen                                  0
Nombre                                        0
Producto                                      0
Asesor                                        0
Origen                                        0
Seguimiento                                   6
Cita efetiva                                  9
PDM                                          10
SDC                                          10
Estatus                                       6
¿Por que no hay seguimiento?                104
¿Por que no ha visitado la agencia?         134
¿Por que no hubo prueba de manejo ?         275
¿Por que no hubo solicitud de credito?      276
¿Por que no se ha formalizado la compra?    289
dtype: int64

In [21]:
df[df["Seguimiento"].isnull()]

,Fecha Origen,Nombre,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?
280,2025-06-10 18:57:00,Andres Morgan,GS8,VICTOR MANUEL SANCHEZ ARROYO,GALERIAS TLAXCALA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,2025-06-10 18:53:00,Cesar Xicohtencatl,GS8,VICTOR MANUEL SANCHEZ ARROYO,Gran Patio Tlaxcala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,2025-06-10 18:04:00,Jesus Fernandez,GS8,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,2025-06-10 17:39:00,Agustin .,EMKOO,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,2025-06-10 17:37:00,Claudia Aguilar,GS8,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,2025-06-10 17:17:00,Miguel Angel Perez Mendez,EMZOOM,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df[df["Seguimiento"].isnull()]
## Se conservaron los valores faltantes en Seguimiento, Cita efectiva, PDM y SDC porque 
# no había información suficiente para imputarlos sin inventar datos.

,Fecha Origen,Nombre,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?
280,2025-06-10 18:57:00,Andres Morgan,GS8,VICTOR MANUEL SANCHEZ ARROYO,GALERIAS TLAXCALA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,2025-06-10 18:53:00,Cesar Xicohtencatl,GS8,VICTOR MANUEL SANCHEZ ARROYO,Gran Patio Tlaxcala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,2025-06-10 18:04:00,Jesus Fernandez,GS8,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,2025-06-10 17:39:00,Agustin .,EMKOO,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,2025-06-10 17:37:00,Claudia Aguilar,GS8,LAURA LOPEZ MEJIA,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,2025-06-10 17:17:00,Miguel Angel Perez Mendez,EMZOOM,JOSE MIGUEL RAMIREZ MUÃ‘OZ,PLAZA ANGELOPOLIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# Se usó Int64 para mantener los valores 0-1 y representar los faltantes como <NA>
df["Seguimiento"] = df["Seguimiento"].astype("Int64")
df["Cita efetiva "] = df["Cita efetiva "].astype("Int64")
df["PDM"] = df["PDM"].astype("Int64")
df["SDC"] = df["SDC"].astype("Int64")

In [24]:
df.isnull().sum()

Fecha Origen                                  0
Nombre                                        0
Producto                                      0
Asesor                                        0
Origen                                        0
Seguimiento                                   6
Cita efetiva                                  9
PDM                                          10
SDC                                          10
Estatus                                       6
¿Por que no hay seguimiento?                104
¿Por que no ha visitado la agencia?         134
¿Por que no hubo prueba de manejo ?         275
¿Por que no hubo solicitud de credito?      276
¿Por que no se ha formalizado la compra?    289
dtype: int64

In [25]:
df.columns

Index(['Fecha Origen', 'Nombre', 'Producto', 'Asesor', 'Origen', 'Seguimiento',
       'Cita efetiva ', 'PDM', 'SDC', 'Estatus',
       '¿Por que no hay seguimiento?', '¿Por que no ha visitado la agencia?',
       '¿Por que no hubo prueba de manejo ?',
       '¿Por que no hubo solicitud de credito?',
       '¿Por que no se ha formalizado la compra?'],
      dtype='str')

In [26]:
## Los valores faltantes en las columnas de texto se reemplazaron por No hay registro, 
# ya que no hay manera de imputarlos.

texto = ['Estatus','¿Por que no hay seguimiento?','¿Por que no ha visitado la agencia?','¿Por que no hubo prueba de manejo ?','¿Por que no hubo solicitud de credito?','¿Por que no se ha formalizado la compra?']
df[texto] = df[texto].fillna('No hay registro')

In [27]:
df.isnull().sum()

Fecha Origen                                 0
Nombre                                       0
Producto                                     0
Asesor                                       0
Origen                                       0
Seguimiento                                  6
Cita efetiva                                 9
PDM                                         10
SDC                                         10
Estatus                                      0
¿Por que no hay seguimiento?                 0
¿Por que no ha visitado la agencia?          0
¿Por que no hubo prueba de manejo ?          0
¿Por que no hubo solicitud de credito?       0
¿Por que no se ha formalizado la compra?     0
dtype: int64

In [ ]:
## A manera de resumen y para esclarecer  la razón por la que algunos valores nulos 
# siguen apareciendo, es porque los valores faltantes se conservaron como <NA> para 
# mantener las variables binarias en formato numérico y evitar mezclar string con números.

In [28]:
df.to_csv("Plazas_sin_nulos.csv")