In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('Ventas_por_Asesor.xlsx')
df.head()

,Ventas X Mes,12,7,8,13,6,21,17,17.1,23,...,37,10,Unnamed: 31,Unnamed: 32,178,Unnamed: 34,397,Unnamed: 36,236,Unnamed: 38
0,NaN,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,...,2026-06-01 00:00:00,2026-07-01 00:00:00,NaN,NaN,2024,NaN,2025,NaN,2026,NaN
1,Nombre vendedor,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,811.0,Raking,Acum,Ranking,Acum,Ranking,Acum,Ranking
2,PEDRO GONZALEZ ESPINDOLA,,,1,2,,7,2,3,3,...,4,NaN,88.0,NaN,22,NaN,45,2,21,NaN
3,VICTOR MANUEL SANCHEZ ARRO,,,,,1,1,3,,2,...,3,2,88.0,NaN,11,NaN,51,NaN,26,NaN
4,MIGUEL ANGEL SONDEREGGER,,,,1,2,7,5,2,2,...,NaN,NaN,28.0,6,27,1,1,25,0,17

In [3]:
df = pd.read_excel("Ventas_por_Asesor.xlsx", header=1)

In [4]:
columnas_ventas = df.columns[1:31]

df[columnas_ventas] = df[columnas_ventas].replace(r"^\s*$", np.nan, regex=True)
df[columnas_ventas] = df[columnas_ventas].fillna(0)

## Se identificaron espacios vacíos que no estaban registrados como NaN, 
# por lo que se convirtieron a valores nulos y después se reemplazaron por 0 
# en las columnas de ventas

In [5]:
## Renombré la primera columna como Nombre vendedor y eliminé la fila que repetía 
# ese encabezado, para dejar la estructura de la base organizada.
df = df.rename(columns={"Unnamed: 0": "Nombre vendedor"})
df = df.iloc[1:].reset_index(drop=True)

In [6]:
df.tail()

,Nombre vendedor,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,...,2026-06-01 00:00:00,2026-07-01 00:00:00,Unnamed: 31,Unnamed: 32,2024,Unnamed: 34,2025,Unnamed: 36,2026,Unnamed: 38
47,PEDRO ANTONIO,0,0,0,0,0,0,0,0,0,...,2.0,1.0,26.0,7,0,24,15,8,11,7
48,OBRIAN,0,0,0,0,0,0,0,0,0,...,1.0,0.0,2.0,32,0,24,0,30,2,14
49,FATIMA,0,0,0,0,0,0,0,0,0,...,1.0,1.0,2.0,32,0,24,0,30,2,14
50,RUBEN,0,0,0,0,0,0,0,0,0,...,0.0,0.0,1.0,41,0,24,0,30,1,16
51,Total general,12,7,8,13,6,21,17,17,23,...,37.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Nombre vendedor      52 non-null     str
 1   2024-02-01 00:00:00  52 non-null     object
 2   2024-03-01 00:00:00  52 non-null     object
 3   2024-04-01 00:00:00  52 non-null     object
 4   2024-05-01 00:00:00  52 non-null     object
 5   2024-06-01 00:00:00  52 non-null     object
 6   2024-07-01 00:00:00  52 non-null     object
 7   2024-08-01 00:00:00  52 non-null     object
 8   2024-09-01 00:00:00  52 non-null     object
 9   2024-10-01 00:00:00  52 non-null     object
 10  2024-11-01 00:00:00  52 non-null     object
 11  2024-12-01 00:00:00  52 non-null     object
 12  2025-01-01 00:00:00  52 non-null     object
 13  2025-02-01 00:00:00  52 non-null     object
 14  2025-03-01 00:00:00  52 non-null     object
 15  2025-04-01 00:00:00  52 non-null     object
 16  2025-05-01 00:00:00  52 non-null     object
 17  2025-06-01 00:00:00  52 non-null     float64
 18  2025-07-01 00:00:00  52 non-null     float64
 19  2025-08-01 00:00:00  52 non-null     float64
 20  2025-09-01 00:00:00  52 non-null     float64
 21  2025-10-01 00:00:00  52 non-null     float64
 22  2025-11-01 00:00:00  52 non-null     float64
 23  2025-12-01 00:00:00  52 non-null     float64
 24  2026-01-01 00:00:00  52 non-null     float64
 25  2026-02-01 00:00:00  52 non-null     float64
 26  2026-03-01 00:00:00  52 non-null     float64
 27  2026-04-01 00:00:00  52 non-null     float64
 28  2026-05-01 00:00:00  52 non-null     float64
 29  2026-06-01 00:00:00  52 non-null     float64
 30  2026-07-01 00:00:00  52 non-null     float64
 31  Unnamed: 31          51 non-null     float64
 32  Unnamed: 32          49 non-null     object
 33  2024                 51 non-null     object
 34  Unnamed: 34          49 non-null     object
 35  2025                 51 non-null     object
 36  Unnamed: 36          50 non-null     object
 37  2026                 51 non-null     object
 38  Unnamed: 38          49 non-null     object
dtypes: float64(15), object(23), str(1)
memory usage: 16.0+ KB

In [8]:
## Comprobamos solamente que no haya valores nulos en nuestras columnas asociadas a las ventas
# de asesores
df.iloc[:, 1:31].isnull().sum()

2024-02-01 00:00:00    0
2024-03-01 00:00:00    0
2024-04-01 00:00:00    0
2024-05-01 00:00:00    0
2024-06-01 00:00:00    0
2024-07-01 00:00:00    0
2024-08-01 00:00:00    0
2024-09-01 00:00:00    0
2024-10-01 00:00:00    0
2024-11-01 00:00:00    0
2024-12-01 00:00:00    0
2025-01-01 00:00:00    0
2025-02-01 00:00:00    0
2025-03-01 00:00:00    0
2025-04-01 00:00:00    0
2025-05-01 00:00:00    0
2025-06-01 00:00:00    0
2025-07-01 00:00:00    0
2025-08-01 00:00:00    0
2025-09-01 00:00:00    0
2025-10-01 00:00:00    0
2025-11-01 00:00:00    0
2025-12-01 00:00:00    0
2026-01-01 00:00:00    0
2026-02-01 00:00:00    0
2026-03-01 00:00:00    0
2026-04-01 00:00:00    0
2026-05-01 00:00:00    0
2026-06-01 00:00:00    0
2026-07-01 00:00:00    0
dtype: int64

In [9]:
## Como aclaración, los nulos de las columnas de resumen (suma de ventas y ranking) se dejaron sin cambios 
# porque no representan ventas faltantes, sino un error de valor derivado de la
# ejecución de ceirta fórmula en excel.

In [10]:
df.to_csv("Ventas_por_Asesor_sin_nulos.csv")